=== ARIA-VALUSPA/ARIA-System/Agent-Core/bin/Common/Data/social/bayesnetwork.dtd
<!ELEMENT parameters (parameter*)>
<!ELEMENT parameter (parents,values)>
<!ELEMENT parents (parent*)>
<!ELEMENT parent (#PCDATA)>
<!ELEMENT values (value*)>
<!ELEMENT value (#PCDATA|parentref)*>
<!ELEMENT parentref (#PCDATA|parentref)*>
<!ATTLIST parameter name CDATA #REQUIRED>
<!ATTLIST parent name CDATA #REQUIRED>
<!ATTLIST value name CDATA #REQUIRED>
<!ATTLIST parentref name CDATA #REQUIRED value CDATA #REQUIRED>

=== ARIA-VALUSPA/ARIA-System/Agent-Output/bin/Common/Data/social/socialbayes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE parameters SYSTEM "bayesnetwork.dtd">
<parameters>
	<parameter name="attitude">
		<parents/>
		<values>
			<value name="dominant">0.25</value>
			<value name="submissive">0.25</value>
			<value name="friendly">0.25</value>
			<value name="hostile">0.25</value>
		</values>
	</parameter>
	<parameter name="intention">
		<parents/>
		<values>
			<value name="inform">0.16</value>
			<value name="ask">0.16</value>
			<value name="agree">0.16</value>
			<value name="disagree">0.16</value>
			<value name="accept">0.16</value>
			<value name="deny">0.16</value>
		</values>
	</parameter>
	<parameter name="facialexpression">
		<parents>
			<parent name="attitude"/>
			<parent name="intention"/>
		</parents>
		<values>
			<value name="positive">
				<parentref name="attitude" value="dominant">
					<parentref name="intention" value="inform">0.14</parentref>
					<parentref name="intention" value="ask">0.27</parentref>
					<parentref name="intention" value="agree">0.38</parentref>
					<parentref name="intention" value="disagree">0.12</parentref>
					<parentref name="intention" value="accept">0.23</parentref>
					<parentref name="intention" value="deny">0.33</parentref>
				</parentref>
				<parentref name="attitude" value="submissive">
					<parentref name="intention" value="inform">0.56</parentref>
					<parentref name="intention" value="ask">0.49</parentref>
					<parentref name="intention" value="agree">0.47</parentref>
					<parentref name="intention" value="disagree">0.24</parentref>
					<parentref name="intention" value="accept">0.37</parentref>
					<parentref name="intention" value="deny">0.19</parentref>
				</parentref>
				<parentref name="attitude" value="friendly">
					<parentref name="intention" value="inform">0.75</parentref>
					<parentref name="intention" value="ask">0.79</parentref>
					<parentref name="intention" value="agree">0.92</parentref>
					<parentref name="intention" value="disagree">0.80</parentref>
					<parentref name="intention" value="accept">0.96</parentref>
					<parentref name="intention" value="deny">0.77</parentref>
				</parentref>
				<parentref name="attitude" value="hostile">
					<parentref name="intention" value="inform">0.09</parentref>
					<parentref name="intention" value="ask">0.10</parentref>
					<parentref name="intention" value="agree">0.13</parentref>
					<parentref name="intention" value="disagree">0.04</parentref>
					<parentref name="intention" value="accept">0.09</parentref>
					<parentref name="intention" value="deny">0.07</parentref>
				</parentref>
			</value>
			<value name="negative">
				<parentref name="attitude" value="dominant">
					<parentref name="intention" value="inform">0.31</parentref>
					<parentref name="intention" value="ask">0.48</parentref>
					<parentref name="intention" value="agree">0.39</parentref>
					<parentref name="intention" value="disagree">0.64</parentref>
					<parentref name="intention" value="accept">0.47</parentref>
					<parentref name="intention" value="deny">0.55</parentref>
				</parentref>
				<parentref name="attitude" value="submissive">
					<parentref name="intention" value="inform">0.07</parentref>
					<parentref name="intention" value="ask">0.15</parentref>
					<parentref name="intention" value="agree">0.03</parentref>
					<parentref name="intention" value="disagree">0.28</parentref>
					<parentref name="intention" value="accept">0.20</parentref>
					<parentref name="intention" value="deny">0.22</parentref>
				</parentref>
				<parentref name="attitude" value="friendly">
					<parentref name="intention" value="inform">0.11</parentref>
					<parentref name="intention" value="ask">0.11</parentref>
					<parentref name="intention" value="agree">0.03</parentref>
					<parentref name="intention" value="disagree">0.12</parentref>
					<parentref name="intention" value="accept">0.03</parentref>
					<parentref name="intention" value="deny">0.13</parentref>
				</parentref>
				<parentref name="attitude" value="hostile">
					<parentref name="intention" value="inform">0.75</parentref>
					<parentref name="intention" value="ask">0.73</parentref>
					<parentref name="intention" value="agree">0.66</parentref>
					<parentref name="intention" value="disagree">0.93</parentref>
					<parentref name="intention" value="accept">0.89</parentref>
					<parentref name="intention" value="deny">0.78</parentref>
				</parentref>
			</value>
			<value name="neutral">
				<parentref name="attitude" value="dominant">
					<parentref name="intention" value="inform">0.55</parentref>
					<parentref name="intention" value="ask">0.25</parentref>
					<parentref name="intention" value="agree">0.23</parentref>
					<parentref name="intention" value="disagree">0.24</parentref>
					<parentref name="intention" value="accept">0.30</parentref>
					<parentref name="intention" value="deny">0.12</parentref>
				</parentref>
				<parentref name="attitude" value="submissive">
					<parentref name="intention" value="inform">0.37</parentref>
					<parentref name="intention" value="ask">0.36</parentref>
					<parentref name="intention" value="agree">0.50</parentref>
					<parentref name="intention" value="disagree">0.47</parentref>
					<parentref name="intention" value="accept">0.44</parentref>
					<parentref name="intention" value="deny">0.59</parentref>
				</parentref>
				<parentref name="attitude" value="friendly">
					<parentref name="intention" value="inform">0.14</parentref>
					<parentref name="intention" value="ask">0.11</parentref>
					<parentref name="intention" value="agree">0.05</parentref>
					<parentref name="intention" value="disagree">0.07</parentref>
					<parentref name="intention" value="accept">0.00</parentref>
					<parentref name="intention" value="deny">0.10</parentref>
				</parentref>
				<parentref name="attitude" value="hostile">
					<parentref name="intention" value="inform">0.16</parentref>
					<parentref name="intention" value="ask">0.17</parentref>
					<parentref name="intention" value="agree">0.21</parentref>
					<parentref name="intention" value="disagree">0.03</parentref>
					<parentref name="intention" value="accept">0.02</parentref>
					<parentref name="intention" value="deny">0.15</parentref>
				</parentref>
			</value>
		</values>
	</parameter>
	<parameter name="modality">
	<parents>
			<parent name="attitude"/>
			<parent name="intention"/>
		</parents>
		<values>
			<value name="multimodal">
				<parentref name="attitude" value="dominant">
					<parentref name="intention" value="inform">0.32</parentref>
					<parentref name="intention" value="ask">0.41</parentref>
					<parentref name="intention" value="agree">0.29</parentref>
					<parentref name="intention" value="disagree">0.42</parentref>
					<parentref name="intention" value="accept">0.28</parentref>
					<parentref name="intention" value="deny">0.35</parentref>
				</parentref>
				<parentref name="attitude" value="submissive">
					<parentref name="intention" value="inform">0.23</parentref>
					<parentref name="intention" value="ask">0.16</parentref>
					<parentref name="intention" value="agree">0.19</parentref>
					<parentref name="intention" value="disagree">0.22</parentref>
					<parentref name="intention" value="accept">0.26</parentref>
					<parentref name="intention" value="deny">0.30</parentref>
				</parentref>
				<parentref name="attitude" value="friendly">
					<parentref name="intention" value="inform">0.24</parentref>
					<parentref name="intention" value="ask">0.17</parentref>
					<parentref name="intention" value="agree">0.40</parentref>
					<parentref name="intention" value="disagree">0.33</parentref>
					<parentref name="intention" value="accept">0.36</parentref>
					<parentref name="intention" value="deny">0.31</parentref>
				</parentref>
				<parentref name="attitude" value="hostile">
					<parentref name="intention" value="inform">0.19</parentref>
					<parentref name="intention" value="ask">0.30</parentref>
					<parentref name="intention" value="agree">0.17</parentref>
					<parentref name="intention" value="disagree">0.56</parentref>
					<parentref name="intention" value="accept">0.27</parentref>
					<parentref name="intention" value="deny">0.44</parentref>
				</parentref>
			</value>
			<value name="headonly">
				<parentref name="attitude" value="dominant">
					<parentref name="intention" value="inform">0.21</parentref>
					<parentref name="intention" value="ask">0.06</parentref>
					<parentref name="intention" value="agree">0.39</parentref>
					<parentref name="intention" value="disagree">0.28</parentref>
					<parentref name="intention" value="accept">0.41</parentref>
					<parentref name="intention" value="deny">0.38</parentref>
				</parentref>
				<parentref name="attitude" value="submissive">
					<parentref name="intention" value="inform">0.19</parentref>
					<parentref name="intention" value="ask">0.26</parentref>
					<parentref name="intention" value="agree">0.42</parentref>
					<parentref name="intention" value="disagree">0.36</parentref>
					<parentref name="intention" value="accept">0.43</parentref>
					<parentref name="intention" value="deny">0.44</parentref>
				</parentref>
				<parentref name="attitude" value="friendly">
					<parentref name="intention" value="inform">0.15</parentref>
					<parentref name="intention" value="ask">0.21</parentref>
					<parentref name="intention" value="agree">0.30</parentref>
					<parentref name="intention" value="disagree">0.31</parentref>
					<parentref name="intention" value="accept">0.27</parentref>
					<parentref name="intention" value="deny">0.46</parentref>
				</parentref>
				<parentref name="attitude" value="hostile">
					<parentref name="intention" value="inform">0.09</parentref>
					<parentref name="intention" value="ask">0.12</parentref>
					<parentref name="intention" value="agree">0.55</parentref>
					<parentref name="intention" value="disagree">0.24</parentref>
